/**
 * Manages the paths (file locations) of the game assets.
 */
'use strict';

const CONSTANTS = {
  CONFIGS: {}
};


const CONFIGS = CONSTANTS.CONFIGS;

CONFIGS.FRAME_WIDTH_OUT = 432;
CONFIGS.FRAME_HEIGHT_OUT = 300;
CONFIGS.FRAME_HEIGHT_OUT_SPREAD = 900;
CONFIGS.STATE_WAIT = 0;
CONFIGS.STATE_PLAYING = 1;
CONFIGS.STATE_CLEAR = 2;
CONFIGS.STATE_GAMESET_WAIT = 3;
CONFIGS.DEPTH_BASE_OBJ = 0;
CONFIGS.DEPTH_CONTENTS = 1;
CONFIGS.DEPTH_CONTENTS_G2 = 2;
CONFIGS.DEPTH_CONTENTS_G3 = 3;
CONFIGS.DEPTH_CONTENTS_G4 = 4;
CONFIGS.DEPTH_COVER = 5;
CONFIGS.DEPTH_ALWAYS_ON = 10;
